const Languages = {
    inputText: {
        username: 'Email / Số điện thoại',
        password: 'Mật khẩu',
        forgotPass: 'Quên mật khẩu?',
        or: 'HOẶC',
        continueWithFB: 'Tiếp tục với Facebook',
        continueWithGG: 'Tiếp tục với Google',
        youNotAccount: 'Bạn không có tài khoản? Đăng ký',
        youhaveAccount: 'Bạn đã có tài khoản? Đăng nhập',
        backIndex: 'Quay lại trang đăng nhập',
        recoveryPwd: 'Khôi phục mật khẩu',
        sendEmailRecoveryPwd: 'Gửi email khôi phục mật khẩu',
        name: 'Họ và tên',
        phone: 'Số điện thoại',
        pwd: 'Mật khẩu'
    },
    common: {
        cancel: 'Hủy',
        OK: 'Chọn',
        back: 'Quay lại',
        yes: 'Có',
        no: 'Không',
        close: 'Đóng',
        search: 'Tìm kiếm',
        agree: 'Đồng ý',
        or: 'Hoặc',
        continue: 'Tiếp tục',
    },
    buttonText:{
        createTC: 'Tạo thiệp cưới',
        anyMore: 'Tìm hiểu thêm',
        tryIt: 'Trải nghiệm ngay!',
        scanQr: 'Quét mã thanh toán QR ',
        seeAll: 'Xem tất cả',
        createTypeTC: 'Tạo mẫu thiệp cưới',
        seeBefore: 'Xem trước',
        copylink: 'Copy link',
        payment: 'Trả phí',
        dowloadTc: 'Tải thiệp cưới',
        dowloadClient: 'Tải danh sách khách',
        checkGuest: 'Kiểm tra khách mời',
        delete: 'Xoá thiệp',
        edit: 'Chỉnh sửa'
    },
    errorMsg: {
        noInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!',
    },
    menu: {
        services: 'Dịch vụ',
        customerCare: 'Chăm sóc khách hàng',
        myPage: 'Trang của tôi',
        login: 'Đăng nhập',
        register: 'Đăng ký',
    },
    text: {
        textBanner: 'Chia sẻ khoảnh khắc đặc biệt trong cuộc sống!',
        textHeadTC: 'Tạo thiệp dễ dàng, chia sẻ nhanh chóng, & sửa đổi không giới hạn!',
        creatContent:  'Praesent bibendum, est nec gravida fermentum, massa lacus posuere ex, sed varius ante nibh vitae eros. Cras faucibus pretium enim, sit amet vulputate eros iaculis a. Morbi placerat in est vel rutrum.',
        chooseDs: 'Chọn thiết kế & làm thiệp mời của riêng bạn!' ,
        showFullIf: 'Hiển thị đầy đủ thông tin:', 
        address: 'Địa điểm diễn ra lễ cưới',
        album: 'Album ảnh cưới',
        listCustomer: 'Danh sách khách mời',
        effectOpen: 'Hiệu ứng mở thiệp đẹp & chuyên nghiệp',
        contentEffect: 'Khi Đám cưới di động được mở, Hiệu ứng hoạt hình được hiển thị trên toàn màn hình Và làm cho sự chú ý của khách!',
        timeWork: '09h Sáng - 18h Chiều / Thứ 2 - Thứ 6',
        supportCustormer: 'Hỗ trợ khách hàng',
        bankInf: 'Thông tin ngân hàng',
        typeDs: 'Chọn mẫu thiệp của bạn',
        createaWeddingYourOwn: 'Tạo mẫu cướicủa riêng bạn',
        managerTc: 'Quản lý thiệp cưới',
        seeTC:'Xem thiệp ',
        status: 'Trạng thái',
        date: 'Ngày cưới',
        manager: 'Quản lý',
        free: 'Miễn phí',
        autoDelete: '(Tự động xoá sau 24 ngày)',
        onlyDate: '(Còn 30 ngày)',
        complete: 'Hoàn thành', 
        notrushpay: 'Đừng vội thanh toán!',
        freeDraft: 'Hãy tạo bản nháp miễn phí.',
        beauToday: 'Vào ngày đẹp nhất trong cuộc đời bạn, Hãy tạo thiệp cưới Online với Cuoithoi',
        hot: 'HOT',
        packageServices: 'Các gói dịch vụ',
        only: 'Chỉ với',
        price: '1.000.000đ',
        packAllDs: 'trọn gói thiết kế',
        mUse: '3 tháng sử dụng',
        savePen: 'Lưu bút',
        album:'Album ảnh (20 ảnh)',
        confirmInvite: 'Xác nhận lời mời'
    },
    errorMsg: {
        noInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        sessionExpired: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        userNameRequired: 'Họ và tên không được để trống',
        userNameLength: 'Họ và tên không được ít hơn 8 ký tự',
        userNameRegex: 'Không được chứa ký tự đặc biệt hoặc số',
        errIllegal: 'Mật khẩu không hợp lệ',
        emailNull: 'Email không được để trống',
        emailRegex: 'Email không đúng định dạng',
        cardNull: 'Số CMND/CCCD không được để trống',
        cardRegex: 'Số CMND/CCCD phải là số',
        cardCheck: 'Số CMND/CCCD không hợp lệ',
        pwdNull: 'Mật khẩu không được để trống',
        pwdCheck: 'Mật khẩu không được ít hơn 8 ký tự',
        conFirmPwd: 'Xác nhận mật khẩu không trùng khớp với mật khẩu',
        emptyAmount: 'Bạn chưa nhập số tiền',
        minAmount: 'Số tiền nạp/rút tối thiểu là 100.000 vnđ',
        phoneIsEmpty: 'Số điện thoại không được để trống',
        phoneRegex: 'Số điện thoại không đúng định dạng',
        phoneCount: 'Số điện thoại chỉ được 10 số',
        jobEmpty: 'Nghề nghiệp không được để trống',
        taxIdEmpty: 'Mã số thuế không được để trống',
        taxIdSyntax: 'Mã số thuế không được ít hơn 10 ký tự',
        specialCharacters: 'Không được chứa kí tự đặc biệt',
        birthdayEmpty: 'Ngày sinh ',
        birthdayNotNumber: 'Ngày sinh không đúng định dạng ví dụ: 1970-01-01',
        birthdayAge18: 'Chưa đủ 18 tuổi',
        birthdayAge95: 'Vượt quá 95 tuổi',
        errProvince: 'Thành phố không được bỏ trống',
        errDistrict: 'Quận huyện không được bỏ trống',
        errWard: 'Xã phường không được bỏ trống',
        errFunds: 'Nguồn tiền không được bỏ trống',
        errMoveto: 'Chuyển tới không được bỏ trống',
        errKeyBook: 'Mã sổ không được bỏ trống',
        errMsgOldPwdCompare: 'Mật khẩu cũ bạn nhập không đúng',
        errMsgCurrentPwdCompare: 'Mật khẩu nhập lại không trùng khớp',
        errMsgEmpty: 'Mật khẩu nhập không được để trống',
        errMsgLength: 'Mật khẩu nhập phải từ 8 kí tự trở lên',
        errMsgSpecialChar: 'Mật khẩu nhập không được chứa kí tự đặc biệt',
        errMsgSpaceChar: 'Mật khẩu nhập không được chứa kí tự trống',
        errMsgUpperChar: 'Mật khẩu phải có 1 kí tự in hoa',
        errMsgGender: 'Giới tính không được bỏ trống',
        uploading: 'Đang tải ảnh lên',
        uploadingError: 'Tải ảnh thất bại',
        errStk: 'Số tài khoản hoặc số thẻ vượt quá giới hạn cho phép',
        errStkEmpty: 'Số tài khoản hoặc số thẻ trống',
        errNameEmpty: 'Tên tài khoản ngân hàng trống',
        errBankEmpty: 'Ngân hàng chưa được chọn',
        errMethodMoney: 'Vui lòng cập nhật phương thức nhận tiền',
        errMethodWithdrawMoney: 'Vui lòng cập nhật phương thức rút tiền',
        errChooseMethodMoney: 'Vui lòng chọn phương thức nhận tiền',
        errNoEnoughMoney: 'Hạn mức giao dịch tối thiểu <br />100.000 VND',
        errLimit: 'Số dư hiện tại không đủ để giao dịch',
        updatePwd: 'Xác nhận thay đổi mật khẩu thành công',
        errEmptyBirthday: '01/01/1920',
        errKYC: 'Vui lòng xác thực CMT/CCCD để thực hiện việc rút tiền',
        notKYc: ' chưa xác thực CMT/CCCD'
    },
};


export default Languages
